package com.nous.codecanvas.update;
import android.app.*;import android.content.*;import android.content.pm.*;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.widget.*;
import com.nous.codecanvas.provider.CanvasFileProvider;
import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.util.*;import java.util.concurrent.*;
public final class AppUpdater {
 public static final String MANIFEST="https://raw.githubusercontent.com/zhuquan7237/code-canvas/main/docs/update/latest.json";
 private final Activity a;private final Button button;private final SharedPreferences prefs;private final ExecutorService io=Executors.newSingleThreadExecutor();
 private boolean checking,closed,waitingInstall;private volatile boolean cancel;private volatile HttpURLConnection active;private AlertDialog dialog;private File readyFile;private UpdateManifest available;
 private final int installed;private final String version;
 public AppUpdater(Activity a,Button b){this.a=a;button=b;prefs=a.getSharedPreferences("updates",0);int code=0;String name="?";try{PackageInfo p=a.getPackageManager().getPackageInfo(a.getPackageName(),0);code=p.versionCode;name=p.versionName;}catch(Exception ignored){}installed=code;version=name;button.setText("代码画布 "+version+" · 检查更新");button.setOnClickListener(v -> {if(available!=null)offer();else check(true);});button.setOnLongClickListener(v->{new AlertDialog.Builder(a).setTitle("更新设置").setMultiChoiceItems(new String[]{"启动时自动检查（每 6 小时）"},new boolean[]{prefs.getBoolean("auto",true)},(d,i,on)->prefs.edit().putBoolean("auto",on).apply()).setMessage("检查仅请求公开版本清单，不上传文件内容。下载和安装需要你确认。").setPositiveButton("确定",null).show();return true;});}
 private void ui(Runnable r){a.runOnUiThread(()->{if(!closed&&!a.isDestroyed()&&!a.isFinishing())r.run();});}
 public void onResume(){if(waitingInstall && readyFile!=null && a.getPackageManager().canRequestPackageInstalls()){waitingInstall=false;install();return;}if(prefs.getBoolean("auto",true)&&System.currentTimeMillis()-prefs.getLong("checked",0)>6*60*60*1000L)check(false);}
 public void check(boolean manual){if(checking||closed)return;checking=true;if(manual)button.setText("正在检查更新…");io.execute(()->{try{String json;try{json=readManifest(MANIFEST+"?t="+System.currentTimeMillis());}catch(IOException e){json=readManifest("https://api.github.com/repos/zhuquan7237/code-canvas/contents/docs/update/latest.json?ref=main&t="+System.currentTimeMillis());}UpdateManifest m=UpdateManifest.parse(json);prefs.edit().putLong("checked",System.currentTimeMillis()).apply();ui(()->{checking=false;if(m.versionCode>installed){available=m;button.setText("新版本 "+m.versionName+" · 点击更新");if(manual)offer();}else{button.setText("代码画布 "+version+" · 已是最新版本");if(manual)Toast.makeText(a,"已是最新版本",Toast.LENGTH_SHORT).show();}});}catch(Exception e){ui(()->{checking=false;button.setText("代码画布 "+version+" · 检查更新");if(manual)new AlertDialog.Builder(a).setTitle("检查更新失败").setMessage("无法获取更新清单，请稍后重试。\n"+e.getMessage()).setPositiveButton("重试",(d,w)->check(true)).setNegativeButton("关闭",null).show();});}});}
 private String readManifest(String u)throws IOException {HttpURLConnection c=open(u,false);try(InputStream in=c.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1){if(out.size()+n>65536)throw new IOException("更新清单过大");out.write(b,0,n);}return out.toString("UTF-8");}finally{c.disconnect();}}
 public static boolean trustedDownload(URI u){return "https".equals(u.getScheme())&&u.getUserInfo()==null&&u.getPort()==-1&&("github.com".equals(u.getHost())&&u.getPath().startsWith("/zhuquan7237/code-canvas/releases/download/")||"release-assets.githubusercontent.com".equals(u.getHost())||"objects.githubusercontent.com".equals(u.getHost()));}
 private HttpURLConnection open(String value,boolean apk)throws IOException {URI u=URI.create(value);for(int i=0;i<5;i++){boolean ok=apk?trustedDownload(u):("https".equals(u.getScheme())&&u.getUserInfo()==null&&u.getPort()==-1&&("raw.githubusercontent.com".equals(u.getHost())&&u.getPath().equals("/zhuquan7237/code-canvas/main/docs/update/latest.json")||"api.github.com".equals(u.getHost())&&u.getPath().equals("/repos/zhuquan7237/code-canvas/contents/docs/update/latest.json")));if(!ok)throw new IOException("更新重定向不受信任");HttpURLConnection c=(HttpURLConnection)u.toURL().openConnection();c.setInstanceFollowRedirects(false);c.setConnectTimeout(15000);c.setReadTimeout(20000);c.setRequestProperty("Accept","application/vnd.github.raw+json");c.setRequestProperty("User-Agent","CodeCanvas/"+version);int status=c.getResponseCode();if(status>=300&&status<400){String loc=c.getHeaderField("Location");c.disconnect();if(loc==null)throw new IOException("无效重定向");u=u.resolve(loc);continue;}if(status!=200){c.disconnect();throw new IOException("HTTP "+status);}return c;}throw new IOException("重定向过多");}
 private void offer(){if(available==null)return;dialog=new AlertDialog.Builder(a).setTitle("更新到 "+available.versionName).setMessage(available.notes+"\n\n下载 "+available.size+" 字节。校验完成后由系统确认安装，已有文件会保留。").setPositiveButton("下载并安装",(d,w)->download()).setNegativeButton("稍后",null).setNeutralButton("重新检查",(d,w)->{available=null;check(true);}).show();}
 private void download(){cancel=false;ProgressBar progress=new ProgressBar(a,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(100);int pad=(int)(24*a.getResources().getDisplayMetrics().density);android.widget.LinearLayout box=new android.widget.LinearLayout(a);box.setPadding(pad,pad,pad,pad);box.addView(progress,new android.widget.LinearLayout.LayoutParams(-1,-2));dialog=new AlertDialog.Builder(a).setTitle("正在下载更新").setView(box).setNegativeButton("取消",(d,w)->{cancel=true;HttpURLConnection c=active;if(c!=null)c.disconnect();}).setOnCancelListener(d->{cancel=true;HttpURLConnection c=active;if(c!=null)c.disconnect();}).show();UpdateManifest m=available;io.execute(()->{File part=new File(a.getCacheDir(),"updates/update.part");try{part.getParentFile().mkdirs();HttpURLConnection c=open(m.apkUrl,true);active=c;MessageDigest md=MessageDigest.getInstance("SHA-256");long total=0;try(InputStream in=c.getInputStream();FileOutputStream out=new FileOutputStream(part)){byte[] b=new byte[8192];int n;int previous=-1;while((n=in.read(b))!=-1){if(cancel)throw new IOException("已取消");total+=n;if(total>m.size)throw new IOException("安装包长度不匹配");md.update(b,0,n);out.write(b,0,n);int percent=(int)(total*100/m.size);if(percent!=previous){previous=percent;final int p=percent;ui(()->progress.setProgress(p));}}}finally{c.disconnect();active=null;}if(cancel)throw new IOException("已取消");StringBuilder hash=new StringBuilder();for(byte b:md.digest())hash.append(String.format(Locale.ROOT,"%02x",b));if(total!=m.size||!hash.toString().equalsIgnoreCase(m.sha256))throw new IOException("安装包 SHA-256 校验失败");File target=new File(part.getParentFile(),"update.apk");if(target.exists()&&!target.delete())throw new IOException("无法移除旧安装包");if(!part.renameTo(target))throw new IOException("无法保存安装包");verifyPackage(target);ui(()->{readyFile=target;if(dialog!=null)dialog.dismiss();install();});}catch(Exception e){part.delete();ui(()->{if(dialog!=null)dialog.dismiss();if(!cancel)new AlertDialog.Builder(a).setTitle("更新失败").setMessage(e.getMessage()).setPositiveButton("重试",(d,w)->download()).setNegativeButton("关闭",null).show();});}});}
 private void verifyPackage(File file)throws Exception {int flags=Build.VERSION.SDK_INT>=28?PackageManager.GET_SIGNING_CERTIFICATES:PackageManager.GET_SIGNATURES;PackageManager pm=a.getPackageManager();PackageInfo archive=pm.getPackageArchiveInfo(file.getPath(),flags),current=pm.getPackageInfo(a.getPackageName(),flags);if(archive==null||!a.getPackageName().equals(archive.packageName)||archive.versionCode!=available.versionCode||!available.versionName.equals(archive.versionName))throw new IOException("安装包版本或应用标识不匹配");Signature[] x=Build.VERSION.SDK_INT>=28?archive.signingInfo.getApkContentsSigners():archive.signatures,y=Build.VERSION.SDK_INT>=28?current.signingInfo.getApkContentsSigners():current.signatures;if(x==null||y==null||x.length!=1||y.length!=1||!Arrays.equals(x[0].toByteArray(),y[0].toByteArray()))throw new IOException("安装包签名不匹配");}
 private void install(){if(readyFile==null)return;if(!a.getPackageManager().canRequestPackageInstalls()){waitingInstall=true;dialog=new AlertDialog.Builder(a).setTitle("允许安装更新").setMessage("安装包已校验。请在系统设置中允许代码画布安装应用，然后返回继续。不会修改其他安全设置。").setPositiveButton("去设置",(d,w)->{try{a.startActivity(new Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES,Uri.parse("package:"+a.getPackageName())));}catch(Exception e){Toast.makeText(a,"请在系统设置中允许安装应用",Toast.LENGTH_LONG).show();}}).setNegativeButton("稍后",null).show();return;}Uri uri=new Uri.Builder().scheme("content").authority(a.getPackageName()+CanvasFileProvider.AUTHORITY_SUFFIX).appendPath("updates").appendPath("update.apk").build();Intent intent=new Intent(Intent.ACTION_INSTALL_PACKAGE).setData(uri).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);try{a.startActivity(intent);}catch(Exception e){try{a.startActivity(new Intent(Intent.ACTION_VIEW).setDataAndType(uri,"application/vnd.android.package-archive").addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION));}catch(Exception ex){Toast.makeText(a,"无法打开系统安装器："+ex.getMessage(),Toast.LENGTH_LONG).show();}}}
 public void close(){closed=true;cancel=true;if(active!=null)active.disconnect();if(dialog!=null)dialog.dismiss();io.shutdownNow();}
}
