package com.nous.codecanvas;

import com.nous.codecanvas.util.RenderKind;
import com.nous.codecanvas.util.RenderKindDetector;

import org.junit.Test;

import static org.junit.Assert.assertEquals;

/**
 * Type detection has to work from the document's head alone. The regression these cases guard is a
 * long SVG — the normal shape of AI-generated path art — being classified as XML or plain text
 * because its closing tag sat past a fixed 3000-character sample window.
 */
public class RenderKindDetectorTest {

    @Test
    public void longSvgIsStillSvgEvenWhenTheClosingTagIsFarAway() {
        StringBuilder svg = new StringBuilder("<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\">");
        for (int i = 0; i < 800; i++) {
            svg.append("<path d=\"M").append(i).append(" 0 L").append(i).append(" 100\"/>");
        }
        svg.append("</svg>");
        String content = svg.toString();
        assertEquals("fixture must exceed the old sample window", true, content.length() > 12000);
        assertEquals(RenderKind.SVG, RenderKindDetector.detect("chart.svg", content));
        assertEquals(RenderKind.SVG, RenderKindDetector.detect("pasted", content));
    }

    @Test
    public void selfClosingAndDeclarationLedSvgAreSvg() {
        assertEquals(RenderKind.SVG, RenderKindDetector.detect("icon.svg",
                "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\"/>"));
        assertEquals(RenderKind.SVG, RenderKindDetector.detect("pasted",
                "\n\n  <svg width=\"10\" height=\"10\"><circle r=\"5\"/></svg>"));
    }

    @Test
    public void xmlKeepsItsOwnTypeEvenWhenChildrenLookLikeHtml() {
        String doc = "<?xml version=\"1.0\"?>\n<layout><div>cell</div><p>text</p></layout>";
        assertEquals(RenderKind.XML, RenderKindDetector.detect("structure.xml", doc));
        assertEquals(RenderKind.XML, RenderKindDetector.detect("pasted", doc));
    }

    @Test
    public void htmlDocumentsAndFragmentsStayHtml() {
        assertEquals(RenderKind.HTML, RenderKindDetector.detect("welcome.html",
                "<!DOCTYPE html>\n<html><body><h1>hi</h1></body></html>"));
        assertEquals(RenderKind.HTML, RenderKindDetector.detect("pasted", "<div class=\"card\">hello</div>"));
        assertEquals(RenderKind.HTML, RenderKindDetector.detect("page.htm", "<p>fragment</p>"));
    }

    @Test
    public void commentsAndProloguesDoNotHideTheRootElement() {
        String doc = "<!-- generated by something -->\n<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\""
                + " \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n<svg><rect/></svg>";
        assertEquals(RenderKind.SVG, RenderKindDetector.detect("drawing", doc));
    }

    @Test
    public void proseAndJsonAreNotMarkup() {
        assertEquals(RenderKind.RAW, RenderKindDetector.detect("notes.txt", "just some words"));
        assertEquals(RenderKind.RAW, RenderKindDetector.detect("pasted", "{\"a\": 1}"));
    }

    @Test
    public void emptyContentFallsBackToTheExtension() {
        assertEquals(RenderKind.HTML, RenderKindDetector.detect("a.html", ""));
        assertEquals(RenderKind.SVG, RenderKindDetector.detect("a.svg", "   "));
        assertEquals(RenderKind.XML, RenderKindDetector.detect("a.xml", null));
    }
}
